[package]
name = "bevy_gstreamer"
authors = ["FoxZoOL <zhooul@gmail.com>"]
version = "0.1.0"
edition = "2021"




[dependencies]
gstreamer = "0.20.5"
bevy = { version = "0.10.0", default-features = false }


[dev-dependencies]
bevy = { version = "0.10.0", features = []}


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3