[package]
name = "bevy_gstreamer"
authors = ["FoxZoOL <zhooul@gmail.com>"]
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.10", default-features = false, features = ["bevy_render", "bevy_core_pipeline", "bevy_asset", "bevy_winit", "bevy_pbr", "x11", ] }
thiserror = "1.0"
gstreamer = "0.20"
gstreamer-app = "0.20"
gstreamer-video = "0.20"
glib = "0.17"
crossbeam = "0.8"
image = { version = "0.24", features = ["jpeg"] }
jpeg-decoder = "0.3.0"
bytemuck = { version = "1.13", features = ["derive"] }


[dev-dependencies]
bevy = { version = "0.10" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3